version: '2'
services:
  nginx:
    image: gr4per/nginx-rp:latest
    ports:
     - "8080:8080"
    depends_on:
     - bnp
    labels:
      SERVICE_NAME: 'nginx'
    extra_hosts:
     - 'consul:172.17.0.1'

  bnp:
    build: .
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
     - mysql
     - suppliers
    volumes:
     - .:/home/node/bnp
    labels:
      SERVICE_NAME: 'bnp'
    environment:
      PORT: '3000'
    ports:
     - "3000:3000"

  suppliers:
    image: gr4per/supplierdir:20170125 #TODO: change back to latest once supplierdir is fixed
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
     - mysql
    labels:
      SERVICE_NAME: 'supplier'  # Service name used by Registrator for adding to Consul's service discovery registry.
      SERVICE_TAGS: 'external'
    ports:
     - "3001:3001"
    extra_hosts:
     - 'consul:172.17.0.1'

  mysql:
    image: gr4per/mysql
    depends_on:
     - registrator
    ports:
     - "3306:3306"

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    #restart: always
    depends_on:
     - consul
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    command: ['-ip=172.17.0.1', 'consul://localhost:8500']

  consul:
    image: consul:latest
    network_mode: host
    #restart: always
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap-expect=1', '-bind=172.17.0.1', '-client=0.0.0.0']
