version: '3'
services:
  main:
    build: .
    image: opuscapita/bnp:dev
    volumes:
     - ./config:/home/node/bnp/config
     - ./src:/home/node/bnp/src
     - ./test:/home/node/bnp/test
    command: 'npm run dev'
