version: '2'
services:
  bnp:
    build: .
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
     - mysql
     - suppliers
    volumes:
     - .:/home/node/bnp
    labels:
      SERVICE_NAME: 'bnp'
    environment:
      PORT: '3000'
    ports:
     - "3000:3000"

  suppliers:
    image: gr4per/supplierdir:20170125 #TODO: change back to latest once supplierdir is fixed
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
     - mysql
    labels:
      SERVICE_NAME: 'supplier'  # Service name used by Registrator for adding to Consul's service discovery registry.
      SERVICE_TAGS: 'external'
    ports:
     - "3001:3001"
    extra_hosts:
     - 'consul:172.17.0.1'

  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_DB
      POSTGRES_DB: $POSTGRES_USER
    depends_on:
      - registrator

  apigw:
    image: ocbesbn/api-gw:0.1
    depends_on:
      - postgres
    environment:
      KONG_DATABASE: 'postgres'
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_PORT: $KONG_PG_PORT
      APP_HOST: $HOST
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
    ports:
      - "$GATEWAY_PORT:$GATEWAY_PORT"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    depends_on:
      - postgres

  idpro:
    image: ocbesbn/idpro:0.1
    ports:
     - "$APP_HOST_PORT:$APP_HOST_PORT"
    environment:
      NODE_ENV: $NODE_ENV
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT
      MYSQL_USER: $MYSQL_USER
      MYSQL_DIALECT: $MYSQL_DIALECT
      MYSQL_SERVICE_NAME: $MYSQL_HOST
      APP_HOST: '0.0.0.0'
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
    depends_on:
      - apigw

  api-registry:
    image: ocbesbn/api-registrator:0.1
    ports:
      - "$API_REGISTRY_PORT:$API_REGISTRY_PORT"
    environment:
      CONSUL_HOST: $HOST
      AUTH_SERVER: $AUTH_SERVER
      AUTH_SERVER_PORT: $AUTH_SERVER_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
      KONG_HOST: $KONG_HOST
      KONG_PORT: $KONG_PORT
      API_REGISTRY_PORT: $API_REGISTRY_PORT
    depends_on:
      - idpro

  mysql:
    image: gr4per/mysql
    depends_on:
     - registrator
    ports:
     - "3306:3306"

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    #restart: always
    depends_on:
     - consul
    volumes:
     - /var/run/docker.sock:/tmp/docker.sock
    command: ['-ip=172.17.0.1', 'consul://localhost:8500']

  consul:
    image: consul:latest
    network_mode: host
    #restart: always
    ports:
      - '8400:8400'
      - '8500:8500'
      - '8600:53/udp'
    labels:
      SERVICE_IGNORE: 'true'  # Do not add any of Consul's services to Consul's service discovery registry.
    command: [agent, '-server', '-ui', '-bootstrap-expect=1', '-bind=172.17.0.1', '-client=0.0.0.0']
