version: '2'
services:
  main:
    build: .
#    image: opuscapita/bnp:dev
    #restart: on-failure:5
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
      - mysql
      - supplier
    volumes:
      - .:/home/node/bnp
#      - ../react-components:/var/tmp/base/node_modules/ocbesbn-react-components
    labels:
      SERVICE_NAME: 'bnp'
    environment:
      APPLICATION_NAME: 'bnp'
      HOST_IP: $HOST_IP
      PORT: '3000'
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      REDIS_AUTH: $REDIS_AUTH
      USER_NAME: 'bnp'
      PASSWORD: 'svc_bnp'
      CLIENT_KEY: $CLIENT_KEY
      CLIENT_SECRET: $CLIENT_SECRET
      SCOPE: $SCOPE
    ports:
      - '3000:3000'
    extra_hosts:
      - 'consul:${HOST_IP}'
    command: 'npm run dev'

#  onboarding:
#    image: opuscapita/onboarding:dev
##    build: ../onboarding
#    volumes:
##      - .:/home/node/onboarding
#      - ../react-components:/var/tmp/base/node_modules/ocbesbn-react-components
#    environment:
#      APPLICATION_NAME: 'onboarding'
#      NODE_ENV: $NODE_ENV
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      EXTERNAL_HOST: 52.174.28.41
#      EXTERNAL_PORT: 8080
#      REDIS_AUTH: ${REDIS_AUTH}
#      HOST_IP: ${HOST_IP}
#    depends_on:
#      - mysql
#      - redis
#      - registrator
#    labels:
#      - 'SERVICE_NAME=onboarding'
#      - 'SERVICE_TAGS=external,kong'
#    extra_hosts:
#      - 'consul:${HOST_IP}'
#    ports:
#      - '3002:3002'
#    command: 'npm run dev'

  supplier:
    image: opuscapita/supplier:dev
#    build: ../supplier
#    volumes:
#     - ../supplier:/home/node/supplier
    depends_on:  # as of version 1.9.0 Dockerfile's HEALTHCHECK is not supported yet.
      - mysql
      - isodata
    labels:
      SERVICE_NAME: 'supplier'  # Service name used by Registrator for adding to Consul's service discovery registry.
      SERVICE_TAGS: 'external'
    ports:
      - "3001:3001"
    environment:
      PORT: '3001'
      HOST_IP: $HOST_IP
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      NODE_ENV: 'production'
      REDIS_AUTH: $REDIS_AUTH
    extra_hosts:
      - 'consul:${HOST_IP}'
    command: 'npm run dev'

  postgres:
    image: postgres:9.4
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: $POSTGRES_DB
      POSTGRES_DB: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    depends_on:
      - registrator
  user:
    image: opuscapita/user:dev
#    build: ../user
#    volumes:
#     - ../user:/home/node/user
    depends_on:
      - mysql
      - consul
      - registrator
    labels:
      SERVICE_NAME: 'user'
    extra_hosts:
       - 'consul:${HOST_IP}'
    environment:
      PORT: 3008
      HOST_IP: $HOST_IP
      MYSQL_DATABASE: $MYSQL_DATABASE
      REDIS_AUTH: $REDIS_AUTH
      USER_NAME: 'user'
      PASSWORD: 'svc_user'
      CLIENT_KEY: $CLIENT_KEY
      CLIENT_SECRET: $CLIENT_SECRET
      SCOPE: $SCOPE
    ports:
      - '3008:3008'
    command: 'npm run dev'

  apigw:
    image: ocbesbn/api-gw:dev
    environment:
      KONG_DATABASE: 'postgres'
      KONG_PG_HOST: $KONG_PG_HOST
      KONG_PG_PORT: $KONG_PG_PORT
      APP_HOST: $HOST_IP
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      LOG_PORT: 5000
      LOG_HOST: $LOG_HOST
      HOST: $HOST_IP
      REDIS_HOST: $HOST_IP # TODO: remove after api-gw is using config
      REDIS_PORT: 6379 # TODO: remove after api-gw is using config
      REDIS_AUTH: $REDIS_AUTH # TODO: remove after api-gw is using config
      SERVICE_8001_NAME: 'kong-api'
      SERVICE_8080_NAME: 'kong'
    ports:
      - '8080:8080'
      - '8443:8443'
      - '8001:8001'
      - '7946:7946'
      - '7946:7946/udp'
    depends_on:
      - postgres
      - mysql
    volumes:
      - .:/usr/local/kong/logs

  auth:
    image: opuscapita/auth:dev
#    build: ../auth
#    volumes:
#     - ../auth:/home/node/auth
    ports:
     - '$APP_HOST_PORT:$APP_HOST_PORT'
    environment:
      HOST_IP: $HOST_IP
      NODE_ENV: $NODE_ENV
      APP_HOST: '0.0.0.0'
      APP_HOST_PROTOCOL: $APP_HOST_PROTOCOL
      APP_HOST_PORT: $APP_HOST_PORT
      GATEWAY_SCHEME: $GATEWAY_SCHEME
      GATEWAY_IP: $GATEWAY_IP
      GATEWAY_PORT: $GATEWAY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      REDIS_AUTH: $REDIS_AUTH
      USER_NAME: 'auth'
      PASSWORD: 'svc_auth'
      CLIENT_KEY: $CLIENT_KEY
      CLIENT_SECRET: $CLIENT_SECRET
      SCOPE: $SCOPE
    depends_on:
      - apigw
    extra_hosts:
      - 'consul:${HOST_IP}'
    command: 'npm run dev'

  api-registry:
    image: ocbesbn/api-registrator:dev
#    build: ../api-registrator
    ports:
      - '$API_REGISTRY_PORT:$API_REGISTRY_PORT'
    environment:
      AUTH_SERVER: $AUTH_SERVER
      AUTH_SERVER_PORT: $AUTH_SERVER_PORT
      API_REGISTRY_PORT: $API_REGISTRY_PORT
      GATEWAY_CALLBACK: $GATEWAY_CALLBACK
    depends_on:
      - apigw

  redis:
    image: ocbesbn/redis:latest
    ports:
      - '6379:6379'
    environment:
      REDIS_AUTH: $REDIS_AUTH
    depends_on:
      - registrator


  #ELK stack
#  elasticsearch:
#    image: ocbesbn/elasticsearch:latest
#    environment:
#      # This helps ES out with memory usage
#      - ES_JAVA_OPTS=-Xmx1g -Xms1g
#    depends_on:
#      - registrator
#    ports:
#      - '9200:9200'
#      - '9300:9300'
#
#  logstash:
#    image: ocbesbn/logstash:latest
#    depends_on:
#      - registrator
#    ports:
#      - '5000:5000/udp'
#      - '12201:12201/udp'
#    environment:
#      ELASTICSEARCH_IP: $HOST_IP
#
#  kibana:
#    image: ocbesbn/kibana:latest
#    depends_on:
#      - registrator
#    ports:
#      - '5601:5601'
#    environment:
#      ELASTICSEARCH_IP: $HOST_IP
  #ELK stack

  mysql:
    image: 'mysql:5.6'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    depends_on:
      - registrator

  registrator:
    image: gliderlabs/registrator:latest
    network_mode: host
    #restart: always
    depends_on:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    command: ['-ip=${HOST_IP}', 'consul://localhost:8500']

  consul:
    command: -bootstrap -ui
    image: gliderlabs/consul-server
    labels:
      - 'SERVICE_NAME=consul'
    ports:
      - '8400:8400'
      - '8500:8500'
      - '53:8600/udp'
      - '53:8600'

  isodata:
    image: opuscapita/isodata:dev
#    build: '../isodata'
#    volumes:
#      - ../isodata:/home/node/isodata
    ports:
      - '3006:3006'
    extra_hosts:
      - 'consul:${HOST_IP}'
    depends_on:
      - consul
      - mysql
    labels:
      SERVICE_NAME: isodata
    environment:
      HOST_IP: ${HOST_IP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: '3006'
    command: 'npm run dev'

  einvoice-send:
    image: opuscapita/einvoice-send:dev
    ports:
      - '3007:3007'
    extra_hosts:
      - 'consul:${HOST_IP}'
    depends_on:
      - consul
      - mysql
    labels:
      SERVICE_NAME: einvoice-send
    environment:
      HOST_IP: ${HOST_IP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      PORT: '3007'
    command: 'npm run dev'

  acl:
    image: opuscapita/acl:dev
    labels:
      - 'SERVICE_NAME=acl'
      - 'SERVICE_TAGS=external,kong'
    environment:
      PORT: 3013
      HOST_IP: ${HOST_IP}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
     - '3013:3013'
    depends_on:
      - apigw
    command: 'npm run dev'
