version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deployment script
          command: |
            export andariel_branch=develop
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then export andariel_branch=master; fi

            curl -f --header "Authorization: token $GIT_TOKEN" https://raw.githubusercontent.com/OpusCapita/andariel/$andariel_branch/buildscript.sh > buildscript.sh
            chmod +x buildscript.sh
            ./buildscript.sh opuscapita/$CIRCLE_PROJECT_REPONAME


  copy_to_env:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - run:
          name: Mirror Script
          command: |
            export andariel_branch=develop
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then export andariel_branch=master; fi
            curl -f --header "Authorization: token $GIT_TOKEN" https://raw.githubusercontent.com/OpusCapita/andariel/$andariel_branch/mirrorscript.sh > mirrorscript.sh
            chmod +x mirrorscript.sh
            ./mirrorscript.sh opuscapita/$CIRCLE_PROJECT_REPONAME $FROM_ENV $TO_ENV $GIT_TOKEN

  build_base:
    docker:
      - image: circleci/node:8
    working_directory: ~/build

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - deploy:
          name: Build and push Docker base image
          command: |
            if [ -f "Dockerfile.base" ] ; then 
            docker build -t opuscapita/$CIRCLE_PROJECT_REPONAME:base -f Dockerfile.base .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push opuscapita/$CIRCLE_PROJECT_REPONAME:base
            else
            echo "no Dockerfile.base found, skipping base img build"
            fi

workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - develop
    jobs:
      - build_base
