// this file was auto generated by duriel, don't manually change it!

const de = require('./de');
const en = require('./en');
const sv = require('./sv');
const fi = require('./fi');

module.exports = {de, en, sv, fi };
