// this file was auto generated by duriel, don't manually change it!

const de = require('./de.json');
const en = require('./en.json');
const sv = require('./sv.json');
const fi = require('./fi.json');

module.exports = {de, en, sv, fi };
