// this file was auto generated by duriel, don't manually change it!

const en = require('./en.json');
const de = require('./de.json');
const fi = require('./fi.json');
const sv = require('./sv.json');
const it = require('./it.json');
const fr = require('./fr.json');
const es = require('./es.json');
const pt = require('./pt.json');

module.exports = {en, de, fi, sv, it, fr, es, pt };
